# Generated by Django 5.2.4 on 2025-07-29 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boms', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boms.bom'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_items', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('name', 'version')},
        ),
    ]
