# Generated by Django 5.2.4 on 2025-07-29 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFxInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('viewed', 'Viewed'), ('responded', 'Responded'), ('declined', 'Declined')], default='invited', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rfx_invitations',
            },
        ),
        migrations.CreateModel(
            name='RFxResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('response', models.JSONField(blank=True, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_terms', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('lead_time', models.IntegerField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rfx_responses',
            },
        ),
        migrations.CreateModel(
            name='RFxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type', models.CharField(choices=[('rfi', 'Request for Information'), ('rfp', 'Request for Proposal'), ('rfq', 'Request for Quote')], max_length=10)),
                ('scope', models.TextField(blank=True, null=True)),
                ('criteria', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('evaluation_parameters', models.JSONField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfx_events', to='boms.bom')),
            ],
            options={
                'db_table': 'rfx_events',
            },
        ),
    ]
