# Generated by Django 5.2.4 on 2025-07-29 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfx', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rfx_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfxevent',
            name='parent_rfx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rfx.rfxevent'),
        ),
        migrations.AddField(
            model_name='rfxinvitation',
            name='rfx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='rfx.rfxevent'),
        ),
        migrations.AddField(
            model_name='rfxinvitation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfx_invitations', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='rfxresponse',
            name='rfx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rfx.rfxevent'),
        ),
        migrations.AddField(
            model_name='rfxresponse',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfx_responses', to='vendors.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='rfxinvitation',
            unique_together={('rfx', 'vendor')},
        ),
    ]
